### ISSUE TITLE
port to node canvas

### ISSUE THREAD

**Issue by qschroed** [jnordberg/gif.js#101]
Would open the possibility to render gif from backend from an array of images or do other manipulations without the need of a browser

**Comment by 1j01** [comment]
Check out these existing modules:
- https://github.com/pkrumins/node-gif#readme
- https://github.com/eugeneware/gifencoder#readme
- http://aheckmann.github.io/gm/ (see: https://stackoverflow.com/a/37726992/2624876)

**Comment by cancerberoSgx** [comment]
@1j01 but then I need to use 2 different APIs to support both :(

**Comment by qschroed** [comment]
@1j01 Thx! The gifencoder worked for me as I could just add the array frame by frame from the canvas I used with node canvas, also very straight forward to use.
