### ISSUE TITLE
import / require as module for bundler?

### ISSUE THREAD

**Issue by ebrensi** [jnordberg/gif.js#117]
I have been using `gifjs` for a while and it works great!

My app has grown to the point where just including script tags or concatenating `.js` files is no longer feasible.   I am trying to figure out how to go about importing the main script and worker scripts.  I `npm` installed `gif.js.optimized' but now I'm not sure what to do.

As far as I can tell from `index.js`, the exports of this `npm` package are
```
module.exports = {
  NeuQuant: require('./src/NeuQuant.js'),
  TypedNeuQuant: require('./src/TypedNeuQuant.js'),
  GIFEncoder: require('./src/GIFEncoder.js'),
  LZWEncoder: require('./src/LZWEncoder.js')
};
```

none of which are the `GIF()` constructor.  I am new to this so pardon me if I am missing something obvious.
Would it be something like
```
const GIF = require("gif.js.optimized").GIFEncoder
```
?

And what about the worker?  How do I import that?

I would be happy to submit a pull request documenting how to do these things when I figure it out.

**Comment by ebrensi** [comment]
never mind, I figured it out.  For anyone who may be wondering, the "default export" of this repo as an npm module is not actually the `gif.js` with the `GIF` object that we want to use.  `gif.js` is created by the build script in `/bin`.

**Comment by DaniEzzeddine** [comment]
@ebrensi so in order to use worker I have to provide pass to the gif.js/dist/ in node_modules?

**Comment by ebrensi** [comment]
> @ebrensi so in order to use worker I have to provide pass to the gif.js/dist/ in node_modules?

Hey sorry for taking so long.  I just saw this.  I hope you figured it out by now.  Did you?

**Comment by DaniEzzeddine** [comment]
@ebrensi yep:)

**Comment by ChinonsoO** [comment]
Don't mean to necro post but I'm encountering the same issue. How did you guys figure it out?
