### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < 

### ISSUE THREAD

**Issue by vincerubinetti** [jnordberg/gif.js#33]
Can anyone think of any reason I would be getting such output from gif.js? 

> spawning worker 0 gif.js:1
> spawning worker 1 gif.js:1
> starting frame 1 of 201 gif.js:1
> starting frame 2 of 201 gif.js:1
> Resource interpreted as Script but transferred with MIME type text/html: "file:///C:/Users/Vincent/Desktop/Software/Tools/Gyrographer/App/gif/". gif.js:1
> Uncaught SyntaxError: Unexpected token <

**Comment by ionull** [comment]
@jnordberg Is there any suggestion to use it in a webpack project(like vuejs), since it is a one-js-file project.

**Comment by jnordberg** [comment]
@ionull No, not really. The worker script is loaded through the browsers loading system, maybe that can be monkeypatched to do something but i doubt it.

**Comment by ionull** [comment]
@jnordberg I found something like worker-loader workerjs project which will load worker from file. But in gif.js project we must use a file path instead of worker instance.

**Comment by 1j01** [comment]
See https://github.com/jnordberg/gif.js/issues/58, https://github.com/jnordberg/gif.js/issues/47

**Comment by ionull** [comment]
@1j01 thanks a lot, I used file loader minutes ago, it is now working well :) Blob is not compatible well with some IE browser
