### ISSUE TITLE
Synchronous usage

### ISSUE THREAD

**Issue by photopea** [jnordberg/gif.js#57]
Hi,

Is it possible to use gif.js synchronously, without "finished" event?

I wonder why do you create bindings with DOM etc. GIF encoder should be a tool, which receives ArrayBuffer (uncompressed image) and returns another ArrayBuffer (compressed image). If you want to make Canvas or an Image as an input, it should be built on top of GIF.js, not as the only input method.

**Comment by jnordberg** [comment]
Use the source luke

**Comment by photopea** [comment]
Hi, what source do you mean? Can you add an example of synchronous usage into the .md description?

Who is Luke?
