### ISSUE TITLE
How to trigger "finished" event

### ISSUE THREAD

**Issue by fleduc** [jnordberg/gif.js#69]
My implementation of gif creator is controlled by an other process loop.
I have declared gif this way:

        var gif = new GIF({ workers: 2, quality: 10, debug: true, width: canvas.width, height: canvas.height});
          gif.on('finished', function(blob) {
            window.open(URL.createObjectURL(blob));
          });
        gif.render();

I'm processing all frames (around 300) and add them to gif:

gif.addFrame(context, {copy: true});

Then when I'm finished, I nee to have my Gif animation opened in an other window, but don't know how trigger the "finished" event.

Any help please

**Comment by 1j01** [comment]
You should only call `gif.render` once you're done adding frames. Then `gif.render` should trigger the "finished" event.

**Comment by 1j01** [comment]
`window.open` probably needs to be called during a user action such as a `click` though, so it isn't blocked.

**Comment by fleduc** [comment]
Thanks!

I didn't catch that this render was to be executed only when all frames were added, since I'm working with three.js which render's must be called on every frame... ;-)

Thanks again
