### ISSUE TITLE
How to save the resulting GIF element to a file?

### ISSUE THREAD

**Issue by Zvika88** [jnordberg/gif.js#85]
Cool package, seems to work smoothly and generate a GIF element on the browser, kudos! I'd like to save a local copy and to upload it to a server. How can the GIF be saved and/or uploaded?
Thanks! Z.

**Comment by 1j01** [comment]
For saving to the user's computer, check out [FileSaver.js](https://github.com/eligrey/FileSaver.js/) (in the future there may be a [streaming API](https://streams.spec.whatwg.org/)), and for uploading to a server, well, it depends on the server! Just google e.g. "upload file php" or "upload file node.js" (or "upload blob") (and you might want to look into resumable upload solutions)

**Comment by Zvika88** [comment]
Great, thank you!
