### ISSUE TITLE
GIFDecoder is not defined

### ISSUE THREAD

**Issue by hwlv** [jnordberg/gif.js#86]
var oReq = new XMLHttpRequest();
        oReq.open("GET", imgUrl, true);
        oReq.responseType = "arraybuffer";
        oReq.onload = function (oEvent) {
            var arrayBuffer = oReq.response; // Note: not oReq.responseText
            if (arrayBuffer) {
                gif = new GIFDecoder(arrayBuffer);
                var frames = gif.decompressFrames(true);
                renderGIF(frames);
            }
        };
        oReq.send(null);

**Comment by jnordberg** [comment]
JavaScript GIF **encoding** library, you can't just make up your own classes and methods and create issues when they don't exist 😆
