### ISSUE TITLE
The generated git is too large

### ISSUE THREAD

**Issue by yh4922** [jnordberg/gif.js#98]
The same gif using Photoshop to generate, quality will be much better, the size is much smaller, there is a solution？

**Comment by cuixiping** [comment]
To generate smaller size file, you should modify `LZWEncoder.js` and `NeuQuant.js` a lot.
I tried and reduced about 50% size, but still larger than all image processing softwares.

**Comment by ChangMM** [comment]
@cuixiping  Could you please share the way how you optimize the `LZWEncoder.js` and `NeuQuant.js`?
